version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/docker_rails
      - tmp-data:/docker_rails/tmp
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - tmp-data:/docker_rails/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  tmp-data:
  db-data: