version: '3'
services:
  app: &app_base
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    volumes:
      - .:/docker_rails
      - tmp-data:/docker_rails/tmp/sockets
    tty: true
    stdin_open: true
    depends_on:
      - db
      - selenium_chrome
  webpack-dev-server:
    <<: *app_base
    command: "bin/webpack-dev-server"
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    depends_on:
      - app
    tty: false
    stdin_open: false
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - tmp-data:/docker_rails/tmp/sockets
    ports:
      - 80:80
    depends_on:
      - app
  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
volumes:
  tmp-data:
  db-data: